#!/bin/bash

gpio=$1

if [ "$2" == "-v" ]; then
    arg2=$2
    echo "/home/pi/bin/piHeatingLCD/print-to-lcd.py -g $gpio $arg2"
    python /home/pi/bin/piHeatingLCD/print-to-lcd.py -g $gpio $arg2
else
    python /home/pi/bin/piHeatingLCD/print-to-lcd.py -g $gpio #>> /dev/null 2>&1
fi
